# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mock_collector_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmock_collector_service.proto\"\x0e\n\x0c\x43learRequest\"\x0f\n\rClearResponse\"\x12\n\x10GetTracesRequest\"#\n\x11GetTracesResponse\x12\x0e\n\x06traces\x18\x01 \x03(\x0c\"\x13\n\x11GetMetricsRequest\"%\n\x12GetMetricsResponse\x12\x0f\n\x07metrics\x18\x01 \x03(\x0c\x32\xb1\x01\n\x14MockCollectorService\x12(\n\x05\x63lear\x12\r.ClearRequest\x1a\x0e.ClearResponse\"\x00\x12\x35\n\nget_traces\x12\x11.GetTracesRequest\x1a\x12.GetTracesResponse\"\x00\x12\x38\n\x0bget_metrics\x12\x12.GetMetricsRequest\x1a\x13.GetMetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mock_collector_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLEARREQUEST']._serialized_start=32
  _globals['_CLEARREQUEST']._serialized_end=46
  _globals['_CLEARRESPONSE']._serialized_start=48
  _globals['_CLEARRESPONSE']._serialized_end=63
  _globals['_GETTRACESREQUEST']._serialized_start=65
  _globals['_GETTRACESREQUEST']._serialized_end=83
  _globals['_GETTRACESRESPONSE']._serialized_start=85
  _globals['_GETTRACESRESPONSE']._serialized_end=120
  _globals['_GETMETRICSREQUEST']._serialized_start=122
  _globals['_GETMETRICSREQUEST']._serialized_end=141
  _globals['_GETMETRICSRESPONSE']._serialized_start=143
  _globals['_GETMETRICSRESPONSE']._serialized_end=180
  _globals['_MOCKCOLLECTORSERVICE']._serialized_start=183
  _globals['_MOCKCOLLECTORSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
