name: Build and Push aws-distro-opentelemetry-node-autoinstrumentation
description: |
  This action assumes that the repo was checked out. Builds and pushes/loads tarball and image files. Also performs scan
  of the resultant image.

inputs:
  aws-region:
    required: false
    description: "AWS Region, required only if push_image is true"
  image_uri_with_tag:
    required: true
    description: "Image URI with Tag"
  image_registry:
    required: false
    description: "Image Registry, required only if push_image is true"
  snapshot-ecr-role:
    required: false
    description: "IAM Role used for pushing to snapshot ecr, required only if push_image is true"
  push_image:
    required: true
    description: "Whether push image to ECR"
  load_image:
    required: true
    description: "Whether load the image for the following use, only load in PR build"
  node_version:
    required: true
    description: "The node version used in actions"
  package_name:
    required: true
    description: "The package name"
  os:
    required: true
    description: "The os"
  trivyignore-file:
    required: false
    default: ''
    description: "Path to the .trivyignore.yaml file to use for image scan"

runs:
  using: "composite"
  steps:
    - name: Action verification
      if: ${{ (inputs.load_image == false || inputs.load_image == 'false') && (inputs.push_image == false || inputs.push_image == 'false') }}
      shell: bash
      run: |
        echo "At least one of push_image or load_image must be true" 
        exit 1

    - name: Set up
      uses: ./.github/workflows/actions/set_up
      with:
        node_version: ${{ inputs.node_version }}
        package_name: ${{ inputs.package_name }}
        os: ${{ inputs.os }}
        run_unit_tests: true

    - name: Configure AWS Credentials
      if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
      with:
        role-to-assume: ${{ inputs.snapshot-ecr-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install Dependencies, Compile, and Build Tarball
      id: staging_tarball_build
      shell: bash
      run: |
        npm install
        npm run compile
        cd aws-distro-opentelemetry-node-autoinstrumentation
        npm pack

    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

    - name: Login to private AWS ECR
      if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 #v3.5.0
      with:
        registry: ${{ inputs.image_registry }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    # Per https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html, it is possible to
    # make unauthorized calls to get public ECR images (needed to build the ADOT Node docker image), but
    # it can fail if you previously authenticated to a public repo. Adding this step to log out, so we
    # ensure we can make unauthenticated call. This is important for making the pr_build workflow run on
    # PRs created from forked repos.
    - name: Logout of public AWS ECR
      shell: bash
      run: docker logout public.ecr.aws

    - name: Build and push image according to input
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
      with:
        push: ${{ inputs.push_image }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: ${{ inputs.image_uri_with_tag }}
        load: ${{ inputs.load_image }}

    - name: Perform image scan
      uses: ./.github/workflows/actions/image_scan
      with:
        image-ref: ${{ inputs.image_uri_with_tag }}
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
        logout: 'true'
        trivyignore-file: ${{ inputs.trivyignore-file }}