// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { Context, Counter, Histogram, Meter, diag } from '@opentelemetry/api';
import { ReadableSpan, Span, SpanProcessor } from '@opentelemetry/sdk-trace-base';
import { buildAttributes } from './span-metrics-attributes-builder';
import { LIB_VERSION, LIB_VERSION_ATTR, SCHEMA_ATTR, SCHEMA_VERSION } from './identity';
import * as holder from './internal/open-telemetry-holder';

// Instrumentation scope name for the metrics this extension emits. Dotted namespace with a
// snake_case leaf, per OpenTelemetry naming conventions (lowercase, dots as delimiter, no hyphens),
// and free of the reserved 'aws' token. Kept identical to the Java extension so both stay in lockstep.
const SCOPE_NAME = 'cloudwatch.plugin.otel.span_metrics';

const CALLS_METRIC = 'traces.span.metrics.calls';
const DURATION_METRIC = 'traces.span.metrics.duration';

// SpanMetricsConnector default boundaries expressed in seconds (spec §1).
const DURATION_BUCKETS_SECONDS = [0.002, 0.004, 0.006, 0.008, 0.01, 0.05, 0.1, 0.2, 0.4, 0.8, 1, 1.4, 2, 5, 10, 15];

/**
 * Generates request metrics from every recorded span, using the SpanMetricsConnector metric names
 * and dimensions. Paired with a record-forcing sampler it sees 100% of spans regardless of the
 * trace sampling rate. It also stamps identity/dedup attributes (spec §6) on each span at start, so
 * the backend can skip regenerating metrics for a span the extension already metered.
 */
export class SpanMetricsProcessor implements SpanProcessor {
  // Initialized on the first onEnd() once the host has supplied a MeterProvider (late-bind).
  private calls: Counter | undefined;
  private duration: Histogram | undefined;

  onStart(span: Span, _parentContext: Context): void {
    // Dedup + schema/lib markers: presence of the schema attribute tells the backend this span's
    // metrics were already generated by the extension, so it must skip regenerating them.
    //
    // Only stamp when a MeterProvider is bound. The marker is written here (onStart) because the span
    // is immutable by onEnd, but the metric is emitted later in onEnd. If no provider is bound (e.g.
    // OTEL_METRICS_EXPORTER=none, so onEnd can generate nothing) we must NOT mark, or the backend
    // would skip a span that was never metered by anyone and the metric would be lost. The narrow
    // residual — a provider that is torn down between onStart and onEnd — is an accepted shutdown-time
    // race, not a steady-state loss.
    //
    // Guarded so a failure here can never propagate into the host application's span pipeline.
    try {
      if (!holder.hasProvider()) {
        return;
      }
      span.setAttribute(SCHEMA_ATTR, SCHEMA_VERSION);
      span.setAttribute(LIB_VERSION_ATTR, LIB_VERSION);
    } catch (e) {
      diag.warn('Failed to stamp span metrics attributes', e);
    }
  }

  onEnd(span: ReadableSpan): void {
    try {
      if (!this.ensureInstruments()) {
        return;
      }
      const attributes = buildAttributes(span);
      this.calls!.add(1, attributes);
      // hrtime duration [seconds, nanos] -> seconds as a double (spec §1).
      const [seconds, nanos] = span.duration;
      this.duration!.record(seconds + nanos / 1e9, attributes);
    } catch (e) {
      diag.warn('Failed to record span metrics', e);
    }
  }

  forceFlush(): Promise<void> {
    return Promise.resolve();
  }

  shutdown(): Promise<void> {
    return Promise.resolve();
  }

  private ensureInstruments(): boolean {
    if (this.calls !== undefined) {
      return true;
    }
    const meterProvider = holder.get();
    if (meterProvider === undefined) {
      return false;
    }
    const meter: Meter = meterProvider.getMeter(SCOPE_NAME);
    this.duration = meter.createHistogram(DURATION_METRIC, {
      unit: 's',
      advice: { explicitBucketBoundaries: DURATION_BUCKETS_SECONDS },
    });
    // {call} is the UCUM annotation for counted things, matching OTel semconv counter conventions
    // (cf. {request}, {operation}). The collector spanmetrics connector leaves the unit unset; the
    // annotation is preferred because it states what is being counted.
    this.calls = meter.createCounter(CALLS_METRIC, { unit: '{call}' });
    return true;
  }
}
