name: Release CloudWatch Plugin for OpenTelemetry

on:
  workflow_dispatch:
    inputs:
      cloudwatch-plugin-otel-version:
        description: The version to tag the release with, e.g., 1.2.0
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Set up Node and run Unit Tests
        uses: ./.github/actions/set_up
        with:
          node_version: "24"
          package_name: "@aws/cloudwatch-plugin-otel"
          os: ubuntu-latest
          run_unit_tests: true

      - name: Build Tarball
        working-directory: cloudwatch-plugin-otel
        run: npm pack

      - name: Validate project version matches workflow input
        run: |
          cloudwatchPluginVersion=$(node -p "require('./cloudwatch-plugin-otel/package.json').version")
          if [[ ! "$cloudwatchPluginVersion" == "${{ inputs.cloudwatch-plugin-otel-version }}" ]]; then
            echo "Input version '${{ inputs.cloudwatch-plugin-otel-version }}' does not match with the CloudWatch Plugin project version '$cloudwatchPluginVersion'"
            exit 1
          fi

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Publish to npm
        working-directory: cloudwatch-plugin-otel
        env:
          NPM_CONFIG_PROVENANCE: true
        run: npm publish

      - name: Create GH release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          gh release create --target "$GITHUB_REF_NAME" \
            --title "Release cloudwatch-plugin-otel v${{ inputs.cloudwatch-plugin-otel-version }}" \
            --notes "Please refer to the [Changelog](https://github.com/aws-observability/aws-otel-js-instrumentation/blob/main/cloudwatch-plugin-otel/CHANGELOG.md) for more details" \
            --draft \
            "cloudwatch-plugin-otel/v${{ inputs.cloudwatch-plugin-otel-version }}"
